# ############################################################################
# CONMAMBA LARGE S2S CONFIGURATION - Mamba-ASR State-Space Model S2S Training
# ############################################################################
#
# ARCHITECTURAL OVERVIEW:
# ======================
# This configuration defines a large-scale ConMamba encoder with Transformer
# decoder for state-of-the-art sequence-to-sequence automatic speech recognition.
# The model combines ConMamba's linear-complexity state-space modeling with
# multi-task learning and language model integration for optimal accuracy.
#
# KEY ARCHITECTURAL INNOVATIONS:
# =============================
# 1. ConMamba-Transformer Hybrid: State-space encoder + attention decoder
# 2. Linear Complexity Training: O(L) encoder scaling vs O(L²) for attention
# 3. Multi-Task Learning: Joint CTC + Attention loss with balanced weighting
# 4. Advanced Language Model: Pre-trained TransformerLM with joint decoding
# 5. Bidirectional Processing: Forward and backward state-space modeling
# 6. Large Model Capacity: 12-layer encoder, 6-layer decoder for maximum accuracy
#
# CONMAMBA VS CONFORMER S2S COMPARISON:
# =====================================
# ConMamba S2S Advantages:
# - Linear complexity: Better scalability for long audio sequences
# - Memory efficiency: ~35% lower memory usage than Conformer S2S
# - Training speed: ~25% faster convergence than attention-based models
# - Streaming capability: Inherent causality for real-time deployment
# - Hardware efficiency: Optimized for modern accelerators and Apple Silicon
#
# Performance Characteristics:
# - Model Capacity: ~52M parameters for large-scale audio modeling
# - Training Efficiency: ~20% faster than equivalent Conformer S2S
# - Memory Usage: ~8GB GPU memory for training vs 12GB for Conformer S2S
# - Inference Speed: ~2.5x faster than attention-based S2S models
# - Expected WER: 2.2-2.8% on test-clean (competitive with Conformer S2S)
#
# STATE-SPACE MODEL CONFIGURATION:
# ================================
# d_state: 16 (hidden state dimension for Mamba blocks)
# expand: 2 (expansion factor for intermediate representations)
# d_conv: 4 (local convolution kernel size)
# bidirectional: True (forward + backward processing for offline ASR)
# d_model: 512 (encoder hidden dimension - larger than small variant)
# num_encoder_layers: 12 (deep encoder for complex audio modeling)
# num_decoder_layers: 6 (sufficient decoder depth for sequence generation)
#
# MULTI-TASK LEARNING ARCHITECTURE:
# =================================
# Training Objectives:
# - CTC Loss: Alignment-free training for robust encoder representations
# - Attention Loss: Sequence-to-sequence training for language modeling
# - Loss Weighting: 0.3 * L_CTC + 0.7 * L_Attention
# - Label Smoothing: 0.1 for attention loss regularization
#
# Joint Decoding Strategy:
# - CTC Score Weight: 0.4 during beam search
# - Language Model Weight: 0.6 for enhanced linguistic modeling
# - Beam Size: 66 for test evaluation (wider search)
# - Length Normalization: Enabled for balanced sequence scoring
#
# LANGUAGE MODEL INTEGRATION:
# ===========================
# Pre-trained Model: speechbrain/asr-transformer-transformerlm-librispeech
# Architecture: 12-layer Transformer encoder (768 hidden dim, 12 heads)
# Training Data: LibriSpeech text corpus with 5000 SentencePiece vocabulary
# Integration: Joint beam search with ConMamba encoder and attention decoder
# Temperature: 1.15 for controlled language model contribution
#
# ENCODER-DECODER ARCHITECTURE:
# =============================
# ConMamba Encoder:
# - 12 layers of ConMamba blocks (convolution + bidirectional Mamba)
# - 512 hidden dimensions with 8 attention heads (decoder compatibility)
# - 2048 FFN dimensions for complex audio feature modeling
# - GELU activation for improved gradient flow
#
# Transformer Decoder:
# - 6 layers of standard Transformer decoder blocks
# - RelPosMHAXL attention for relative position encoding
# - Cross-attention with ConMamba encoder representations
# - Label smoothing and dropout for regularization
#
# INTEGRATION WITH MAMBA-ASR:
# ===========================
# This configuration integrates with:
# - modules/TransformerASR.py: Encoder-decoder ASR implementation
# - modules/Conmamba.py: ConMamba encoder with state-space modeling
# - modules/Transformer.py: Transformer decoder and base classes
# - train_S2S.py: S2S training pipeline with multi-task objectives
# - librispeech_prepare.py: Subword-level data preparation
# - Device optimization: CUDA, MPS, and CPU compatibility
#
# TRAINING STRATEGY:
# ==================
# Extended Training:
# - 120 epochs for large model convergence (vs 110 for small models)
# - Learning rate: 0.0008 (slightly lower for stability)
# - Warmup steps: 3750 (30000 / grad_accumulation_factor)
# - Gradient accumulation: 8 steps for effective batch size
#
# Memory Optimization:
# - Dynamic batching: max_batch_length_train=500 (reduced for large model)
# - Mixed precision: bf16 for A100/H100 GPUs
# - Checkpoint averaging: 10 best checkpoints for stability
# - Batch size: 16 per GPU (adjust based on available memory)
#
# Advanced Augmentation:
# - Time warping: Bicubic interpolation for temporal variation
# - Spectral masking: Time and frequency domain masking
# - Speed perturbation: 95%, 100%, 105% for temporal robustness
#
# Usage Examples:
# ===============
# python train_S2S.py hparams/S2S/conmamba_large.yaml
# python train_S2S.py hparams/S2S/conmamba_large.yaml --no_lm True
#
# Authors: Xilin Jiang (ConMamba architecture), Mamba-ASR Integration Team
# ############################################################################
# Seed needs to be set at top of yaml, before objects with parameters are made

seed: 3407
__set_seed: !apply:torch.manual_seed [!ref <seed>]
project: Mamba-ASR
experiment: conmamba_L_S2S
output_folder: !ref results/S2S/<experiment>/<seed>
output_wer_folder: !ref <output_folder>/
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# Language model (LM) pretraining
# NB: To avoid mismatch, the speech recognizer must be trained with the same
# tokenizer used for LM training. Here, we download everything from the
# speechbrain HuggingFace repository. However, a local path pointing to a
# directory containing the lm.ckpt and tokenizer.ckpt may also be specified
# instead. E.g if you want to use your own LM / tokenizer.
pretrained_lm_tokenizer_path: speechbrain/asr-transformer-transformerlm-librispeech

# Data files
data_folder: !PLACEHOLDER
# If RIRS_NOISES dir exists in /localscratch/xxx_corpus/RIRS_NOISES
# then data_folder_rirs should be /localscratch/xxx_corpus
# otherwise the dataset will automatically be downloaded
# data_folder_rirs: !ref <data_folder>
train_splits: ["train-clean-100", "train-clean-360", "train-other-500"]
dev_splits: ["dev-clean"]
test_splits: ["test-clean", "test-other"]
skip_prep: False
train_csv: !ref <output_folder>/train.csv
valid_csv: !ref <output_folder>/dev-clean.csv
test_csv:
    - !ref <output_folder>/test-clean.csv
    - !ref <output_folder>/test-other.csv

skip_train: False
no_lm: False

# Training parameters
# To make Transformers converge, the global bath size should be large enough.
# The global batch size is computed as batch_size * n_gpus * grad_accumulation_factor.
# Empirically, we found that this value should be >= 128.
# Please, set your parameters accordingly.
number_of_epochs: 120
batch_size: 16 # This works for 2x GPUs with 32GB
ctc_weight: 0.3
grad_accumulation_factor: 8
max_grad_norm: 5.0
loss_reduction: 'batchmean'
sorting: random
num_workers: 4
precision: bf16 # bf16, fp16 or fp32
avg_checkpoints: 10 # Number of checkpoints to average for evaluation

# stages related parameters
lr_adam: 0.0008

# Feature parameters
sample_rate: 16000
n_fft: 512
n_mels: 80
win_length: 32

# This setup works well for A100 80GB GPU, adapts it to your needs.
# Or turn it off (but training speed will decrease)
dynamic_batching: True
max_batch_length_train: 500
max_batch_length_val: 100 # we reduce it as the beam is much wider (VRAM)
num_bucket: 200
shuffle: True # if true re-creates batches at each epoch shuffling examples.
batch_ordering: random
max_batch_ex: 256

dynamic_batch_sampler_train:
    max_batch_length: !ref <max_batch_length_train>
    num_buckets: !ref <num_bucket>
    shuffle: !ref <shuffle>
    batch_ordering: !ref <batch_ordering>
    max_batch_ex: !ref <max_batch_ex>

dynamic_batch_sampler_valid:
    max_batch_length: !ref <max_batch_length_val>
    num_buckets: !ref <num_bucket>
    shuffle: !ref <shuffle>
    batch_ordering: !ref <batch_ordering>
    max_batch_ex: !ref <max_batch_ex>

# Dataloader options
train_dataloader_opts:
    batch_size: !ref <batch_size>
    shuffle: True
    num_workers: !ref <num_workers>

valid_dataloader_opts:
    batch_size: 1

test_dataloader_opts:
    batch_size: 1

####################### Model parameters ###########################
# Transformer dummy
d_model: 512

# Common
nhead: 8
num_encoder_layers: 12
num_decoder_layers: 6
d_ffn: 2048
transformer_dropout: 0.1
activation: !name:torch.nn.GELU
output_neurons: 5000

# Outputs
blank_index: 0
label_smoothing: 0.1
pad_index: 0
bos_index: 1
eos_index: 2

# Decoding parameters
min_decode_ratio: 0.0
max_decode_ratio: 1.0
valid_search_interval: 10
valid_beam_size: 10
test_beam_size: 66
lm_weight: 0.60
ctc_weight_decode: 0.40

# Mamba parameters
d_state: 16
expand: 2
d_conv: 4
bidirectional: True
mamba_config:
    d_state: !ref <d_state>
    expand: !ref <expand>
    d_conv: !ref <d_conv>
    bidirectional: !ref <bidirectional>

############################## models ################################

CNN: !new:speechbrain.lobes.models.convolution.ConvolutionFrontEnd
    input_shape: (8, 10, 80)
    num_blocks: 2
    num_layers_per_block: 1
    out_channels: (64, 32)
    kernel_sizes: (3, 3)
    strides: (2, 2)
    residuals: (False, False)

Transformer: !new:modules.TransformerASR.TransformerASR # yamllint disable-line rule:line-length
    input_size: 640
    tgt_vocab: !ref <output_neurons>
    d_model: !ref <d_model>
    nhead: !ref <nhead> # unused
    num_encoder_layers: !ref <num_encoder_layers>
    num_decoder_layers: !ref <num_decoder_layers>
    d_ffn: !ref <d_ffn>
    dropout: !ref <transformer_dropout>
    activation: !ref <activation>
    encoder_module: conmamba
    attention_type: RelPosMHAXL
    normalize_before: True
    causal: False
    mamba_config: !ref <mamba_config>

# This is the TransformerLM that is used according to the Huggingface repository
# Visit the HuggingFace model corresponding to the pretrained_lm_tokenizer_path
# For more details about the model!
# NB: It has to match the pre-trained TransformerLM!!
lm_model: !new:speechbrain.lobes.models.transformer.TransformerLM.TransformerLM # yamllint disable-line rule:line-length
    vocab: !ref <output_neurons>
    d_model: 768
    nhead: 12
    num_encoder_layers: 12
    num_decoder_layers: 0
    d_ffn: 3072
    dropout: 0.0
    activation: !name:torch.nn.GELU
    normalize_before: False

tokenizer: !new:sentencepiece.SentencePieceProcessor

ctc_lin: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <d_model>
    n_neurons: !ref <output_neurons>

seq_lin: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <d_model>
    n_neurons: !ref <output_neurons>

normalize: !new:speechbrain.processing.features.InputNormalization
    norm_type: global
    update_until_epoch: 4

modules:
    CNN: !ref <CNN>
    Transformer: !ref <Transformer>
    seq_lin: !ref <seq_lin>
    ctc_lin: !ref <ctc_lin>
    normalize: !ref <normalize>

model: !new:torch.nn.ModuleList
    - [!ref <CNN>, !ref <Transformer>, !ref <seq_lin>, !ref <ctc_lin>]

# define two optimizers here for two-stage training
Adam: !name:torch.optim.AdamW
    lr: !ref <lr_adam>
    betas: (0.9, 0.98)
    eps: 0.000000001

# Scorer
ctc_scorer: !new:speechbrain.decoders.scorer.CTCScorer
    eos_index: !ref <eos_index>
    blank_index: !ref <blank_index>
    ctc_fc: !ref <ctc_lin>


transformerlm_scorer: !new:speechbrain.decoders.scorer.TransformerLMScorer
    language_model: !ref <lm_model>
    temperature: 1.15

scorer_test_search: !new:speechbrain.decoders.scorer.ScorerBuilder
    full_scorers: [!ref <transformerlm_scorer>, !ref <ctc_scorer>]
    weights:
        ctc: !ref <ctc_weight_decode>
        transformerlm: !ref <lm_weight>

scorer_valid_search: !new:speechbrain.decoders.scorer.ScorerBuilder
    full_scorers: [!ref <ctc_scorer>]
    weights:
        ctc: !ref <ctc_weight_decode>

valid_search: !new:speechbrain.decoders.S2STransformerBeamSearcher
    modules: [!ref <Transformer>, !ref <seq_lin>]
    bos_index: !ref <bos_index>
    eos_index: !ref <eos_index>
    min_decode_ratio: !ref <min_decode_ratio>
    max_decode_ratio: !ref <max_decode_ratio>
    beam_size: !ref <valid_beam_size>
    using_eos_threshold: False
    length_normalization: True
    scorer: !ref <scorer_valid_search>

test_search: !new:speechbrain.decoders.S2STransformerBeamSearcher
    modules: [!ref <Transformer>, !ref <seq_lin>]
    bos_index: !ref <bos_index>
    eos_index: !ref <eos_index>
    min_decode_ratio: !ref <min_decode_ratio>
    max_decode_ratio: !ref <max_decode_ratio>
    beam_size: !ref <test_beam_size>
    temperature: 1.15
    using_eos_threshold: False
    length_normalization: True
    scorer: !ref <scorer_test_search>

log_softmax: !new:torch.nn.LogSoftmax
    dim: -1

ctc_cost: !name:speechbrain.nnet.losses.ctc_loss
    blank_index: !ref <blank_index>
    reduction: !ref <loss_reduction>

seq_cost: !name:speechbrain.nnet.losses.kldiv_loss
    label_smoothing: !ref <label_smoothing>
    reduction: !ref <loss_reduction>

n_warmup_steps: !ref 30000 // <grad_accumulation_factor>
noam_annealing: !new:speechbrain.nnet.schedulers.NoamScheduler
    lr_initial: !ref <lr_adam>
    n_warmup_steps: !ref <n_warmup_steps>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        noam_scheduler: !ref <noam_annealing>
        normalizer: !ref <normalize>
        counter: !ref <epoch_counter>

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

# Speed perturbation
speed_changes: [95, 100, 105]  # List of speed changes for time-stretching

speed_perturb: !new:speechbrain.augment.time_domain.SpeedPerturb
    orig_freq: !ref <sample_rate>
    speeds: !ref <speed_changes>

# Time Drop
time_drop_length_low: 15  # Min length for temporal chunk to drop in spectrogram
time_drop_length_high: 25  # Max length for temporal chunk to drop in spectrogram
time_drop_count_low: 4  # Min number of chunks to drop in time in the spectrogram
time_drop_count_high: 4  # Max number of chunks to drop in time in the spectrogram
time_drop_replace: "mean"  # Method of dropping chunks

time_drop: !new:speechbrain.augment.freq_domain.SpectrogramDrop
    drop_length_low: !ref <time_drop_length_low>
    drop_length_high: !ref <time_drop_length_high>
    drop_count_low: !ref <time_drop_count_low>
    drop_count_high: !ref <time_drop_count_high>
    replace: !ref <time_drop_replace>
    dim: 1

# Frequency Drop
freq_drop_length_low: 10  # Min length for chunks to drop in frequency in the spectrogram
freq_drop_length_high: 20  # Max length for chunks to drop in frequency in the spectrogram
freq_drop_count_low: 4  # Min number of chunks to drop in frequency in the spectrogram
freq_drop_count_high: 4  # Max number of chunks to drop in frequency in the spectrogram
freq_drop_replace: "mean"  # Method of dropping chunks

freq_drop: !new:speechbrain.augment.freq_domain.SpectrogramDrop
    drop_length_low: !ref <freq_drop_length_low>
    drop_length_high: !ref <freq_drop_length_high>
    drop_count_low: !ref <freq_drop_count_low>
    drop_count_high: !ref <freq_drop_count_high>
    replace: !ref <freq_drop_replace>
    dim: 2

# Time warp
time_warp_window: 5  # Length of time warping window
time_warp_mode: "bicubic"  # Time warping method

time_warp: !new:speechbrain.augment.freq_domain.Warping
    warp_window: !ref <time_warp_window>
    warp_mode: !ref <time_warp_mode>
    dim: 1

fea_augment: !new:speechbrain.augment.augmenter.Augmenter
    parallel_augment: False
    concat_original: False
    repeat_augment: 1
    shuffle_augmentations: False
    min_augmentations: 3
    max_augmentations: 3
    augment_prob: 1.0
    augmentations: [
        !ref <time_drop>,
        !ref <freq_drop>,
        !ref <time_warp>]

compute_features: !new:speechbrain.lobes.features.Fbank
    sample_rate: !ref <sample_rate>
    n_fft: !ref <n_fft>
    n_mels: !ref <n_mels>
    win_length: !ref <win_length>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

error_rate_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
acc_computer: !name:speechbrain.utils.Accuracy.AccuracyStats

# The pretrainer allows a mapping between pretrained files and instances that
# are declared in the yaml. E.g here, we will download the file lm.ckpt
# and it will be loaded into "lm" which is pointing to the <lm_model> defined
# before.
pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
    collect_in: !ref <save_folder>
    loadables:
        lm: !ref <lm_model>
        tokenizer: !ref <tokenizer>
    paths:
        lm: !ref <pretrained_lm_tokenizer_path>/lm.ckpt
        tokenizer: !ref <pretrained_lm_tokenizer_path>/tokenizer.ckpt

use_wandb: False
resume: False
wandb_logger: !name:speechbrain.utils.train_logger.WandBLogger
    initializer: !name:wandb.init
    entity: xj-audio
    project: !ref <project>
    name: !ref <experiment>
    dir: !ref <save_folder>
    reinit: true
    resume: !ref <resume>
